### ISSUE TITLE
Resolve compilation errors between the three Factions plugins

### ISSUE THREAD

**Issue by StargateMC** [StargateMC/Regenerator#1]
Due to some unfortunate coding, developers who have forked Factions and made their own plugin have not changed the classpath, causing some weird and wonderful errors when compiling.

This means that during each release, compiling once with FactionsOne integration commented out and then once with - then manually moving the FactionsOneIntegration.class file into the one without it is required.

@markehme, Would you be able to lend your expertise to this problem ? What do I need to do sir?! :D

To Non developers: You don't need to worry about this. Every release posted on SpigotMC.org supports everything, it's just annoying for someone trying to compile Regenerator.

**Comment by markhughes** [comment]
This is basically why I created [FactionsFramework](https://github.com/MarkehMe/FactionsFramework), it's in modules so [each layer is a different project](https://github.com/MarkehMe/FactionsFramework/tree/master/layers) - then using gradle it is all merged together.

Goes a bit like this: Using gradle I [include each project](https://github.com/MarkehMe/FactionsFramework/blob/master/settings.gradle) and then [compile them individually](https://github.com/MarkehMe/FactionsFramework/blob/master/build.gradle#L49). After that, we [merge them together](https://github.com/MarkehMe/FactionsFramework/blob/master/build.gradle#L61-L64).

**Comment by StargateMC** [comment]
@MarkehMe Sounds like I should be using FactionsFramework :P 

Thanks man, that sounds... possibly within my grasp as a novice coder ;)

**Comment by markhughes** [comment]
@DraksterAU you can use it 😃  the API is kind of documented in the wiki.

I need to work on it a bit (a lot): https://github.com/MarkehMe/FactionsFramework/wiki/examples

**Comment by markhughes** [comment]
@DraksterAU do you reckon you could add me on Skype? **markehme**

**Comment by StargateMC** [comment]
No longer an issue @markhughes .. sadly seems MassiveCraft no longer supports factions.
Hope you're well!
