### ISSUE TITLE
Slow or no regeneration?

### ISSUE THREAD

**Issue by Pixiio** [StargateMC/Regenerator#12]
Hi! I'm not sure if the plugin is regenerating our world.. Lots of times (50%) it's giving the following error:
```
02.07 20:32:58 [Server] INFO [Regenerator] [INFO]: Regeneration task is starting...
02.07 20:32:59 [Server] INFO [Regenerator] [INFO]: Regeneration task completed without regenerating any chunks.
```
Is there any reason this error happens? 

Sometimes it does work but the cords seem to be really close to eachother? Also it looks like they stay under X 300 and Z 300. Most of the time the cords are on a Griefprevention claim (it does not reset them, luckily).
```
02.07 20:04:02 [Server] INFO [Regenerator] [INFO]: Regenerating : 226,-197 on world: world
02.07 20:04:07 [Server] INFO [Regenerator] [INFO]: Regenerating : 226,-197 on world: world
```

Or just this..
```
02.07 20:50:31 [Server] INFO [Regenerator] [INFO]: Regeneration task completed after processing 1 chunks on 2 worlds.
```

Config + world config: https://pastebin.com/JmYA7jgG
Minecraft version: 1.11

Thanks in advance!

**Comment by StargateMC** [comment]
Hi Mate,

Coordinates are chunk coordinates. For Block ones youll need to multiply them by 16.
May change this later.

As for only regenerating occasionaly.. you have the interval set to 1 hour.... so that is expected... you may also find if your in the chunk it wont regenerate because of global config.

I see no issue here. Reply if i am wrong.

Regards
Bysokar

**Comment by Pixiio** [comment]
Hi Bysokar,

Ah, I didn't know that that were chunk coordinates. If I have any other problems I'll let you know.

Thanks alot!

**Comment by Pixiio** [comment]
Hi Bysokar,

What I still don't understand is why it's giving this error sometimes:
``
02.07 20:32:58 [Server] INFO [Regenerator] [INFO]: Regeneration task is starting...
02.07 20:32:59 [Server] INFO [Regenerator] [INFO]: Regeneration task completed without regenerating any chunks
``
Even when set loaded chunks to true, playeractive to true etc etc. It has been on last night (with no players, because it's night) and it didn't regenerate so many area's.

**Comment by StargateMC** [comment]
That isnt an error. The task that runs and regenerates chunks doesnt always have something to do.

**Comment by Pixiio** [comment]
What I still don't understand (sorry!) is that we still have sooo many area's that didn't regenerate. It's been on a week now. Note: the area's are **not** in GP/Worldguard claims.
