### ISSUE TITLE
GriefPrevention and Thermos 1.7.10

### ISSUE THREAD

**Issue by Sirse** [StargateMC/Regenerator#13]
Hello!
I want to use Regenerator on my modded server based on Thermos server (mc 1.7.10), but Regenerator doesn't support latest GriefPrevention release for Bukkit 1.7.10
[GriefPreventionIntegration] Detected incompatible version of plugin: GriefPrevention (v9.1), required version: 16

Any chances for backport?

**Comment by StargateMC** [comment]
Hi There

Unlikely! I am currently in the process of making regenerate a plugin that other plugins can hook into rather than the other way around.

It is compatible with factions 2.8.8 + massivecoreforgefixes + perimeter if youd consider switching.

Cheers
Bysokar
