### ISSUE TITLE
Add chunk deletion instead of only regeneration

### ISSUE THREAD

**Issue by srleojaco** [StargateMC/Regenerator#15]
The plugin is great... But why not adding an option to "delete chunks" instead of "regenerating them"?

This will allow to reduce world size....

**Comment by StargateMC** [comment]
Hi @SrLeojaco You'd be best working with the WorldBorder plugins 'trim'. command.

This allows you to set a radius of chunks as the world border, then trim (delete) anything outside that from the world.

Regenerators primary function is to keep the area of the world you want to use fresh.

Sorry for the slow response.
