### ISSUE TITLE
Fixed it up for 1.14.2

### ISSUE THREAD

**Issue by ShiftingKill** [StargateMC/Regenerator#19]
I got it "running" on 1.14.2 with hardly any deprecated stuff, completely fixed WorldGuard integration, but the regenerate commands do not work still. It says the area around me has been regenerated but it doesn't. Any ideas? I know there are a few more deprecated things like refreshchunk and regeneratechunk that are probably the core issue and unfortunately Spigot hardly has any info on it. I really want this to work for 1.14.2 and updated most of the basic java like runtasktimer, runtask, runtasktimerasync...etc.

What I've done:
Fixed deprecated runtasktimer, runtasktimerasync, runtask, all the scheduler stuff and a lot of other fixes of deprecated stuff.
Fixed up WorldGuard integration so it's enabled and detected. WorldGuard 7 (latest)!
100% loads and runs on 1.14.2 with all commands, no errors. But it definitely does not work. There is some critical component missing (is it spigot's fault?)

**Comment by ShiftingKill** [comment]
The only deprecated stuff is:
getName() from the type EntityType
isChunkInUse
refreshChunk
regenerateChunk
Only 4 deprecations! But these seem to be the most intense that Spigot may have axed on this update. This plugin should be super close to being done, 35 warnings are just local variables and/or imports not being used.

**Comment by StargateMC** [comment]
Sorry for the slow response, but without refreshChunk and regenerateChunk the plugin isnt going to work. There will need to be some kind of equivalent going forward that you can switch to, or you'll need to hook MC which isnt going to be fun.

**Comment by StargateMC** [comment]
@shiftingkill, I'm going to release an update with your changes in the next couple of days, including a hard dependency on WorldEdit to gain the ability to regenerate chunks. Thanks :)

**Comment by ShiftingKill** [comment]
I have no idea if I sent them or if it was even good code that I wrote, but hopefully you find a way to regen chunks. I ended up just relying on a database to log all the blocks but if you find any way to get this working or need help I might be able to now. I think I remade your plugin over summer with 0 code experience so that's probably why it didn't work but now I'm almost a year into Java so lmk

**Comment by StargateMC** [comment]
No worries man, what you wrote did fix the issue dealing with yml files :)
I've just released 3.4.0 on SpigotMC, compiled for 1.15.2.
