### ISSUE TITLE
Support all bukkit event system compatible protection plugins

### ISSUE THREAD

**Issue by StargateMC** [StargateMC/Regenerator#3]
By throwing fake block break and place events, Regenerator can test to see if a plugin is preventing unknown players from building in a certain area.

This allows Regenerator to in theory support any bukkit event system compatible plugin, for unclaimed land regeneration.

This will support two things;
- Unclaimed land will be the only thing regenerated when a compatible plugin is not found and this config setting is turned on.
- Players will be able to manually regenerate unclaimed or claimed land, but Regenerator wont be able to tell which claim belongs to a player.

**Comment by sammyt291** [comment]
This will be a fantastic addition! +Support

> when a compatible plugin is not found

Also an option to force this check anyway? as I for one will be using WorldGuard alongside a custom land protection plugin, would be good if the false break check stayed enabled even though WG (or any supported) would be detected.

**Comment by StargateMC** [comment]
It will be a config to turn this on, it will work alongside other plugins.

**Comment by sammyt291** [comment]
Fantastic, Looking forward to using it as soon as that is ready!

**Comment by StargateMC** [comment]
Will be a lil while ;)
I've started on a core plugin and am rewriting regenerator on the side. It will help me push out plugins faster - I have a few ideas for ones my server (and others) could Benefit from.

**Comment by StargateMC** [comment]
Finally finished this @sammyt291... enableUnknownProtectionDetection = true in global.yml will support this.

**Comment by sammyt291** [comment]
> Will be a lil while ;)

:D Thank you for doing it, Still looking for this kind of plugin and now this one ticks all the boxes finally  aha, cheers.
