### ISSUE TITLE
Suggestion to update Regenerator for working with GriefPrevention v16+ 

### ISSUE THREAD

**Issue by ArtNRG** [StargateMC/Regenerator#9]
Dear @Bysokar! 
Seems GriefPrevention v16.x isn't changed much, hope you can update your excellent plugin for working with it.
Best regards, ArtNRG.

**Comment by StargateMC** [comment]
Hey @ArtNRG

Ill release v3.2.3 tonight for you.

Cheers

Bysokar

**Comment by ArtNRG** [comment]
@Bysokar, Should I wait for the update of this plugin or I need to look for a replacement or hire somebody to update it?

**Comment by StargateMC** [comment]
Hi @ArtNRG Please test  the v3.2.3 release I just placed on Spigotmc.org. 
I'll close this off, please raise any bugs that you find as separate issues (I don't expect there to be any).
